name: Build SCSS

on:
  push:
    paths: ['**.scss']
  pull_request:
    branches: [master]
    paths: ['**.scss']

permissions:
  contents: write

jobs:
  Build-SCSS:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: extract_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::$(echo $GITHUB_BASE_REF)"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref ||  github.ref_name }}
      - uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/css/scss/main.scss
          destination: assets/css/main.css
      - name: Add and commit changes to branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Add compiled CSS files'
          git push
