name: Build SCSS

on:
  pull_request:
    branches: [master]
    paths: '**.scss'

permissions:
  contents: write

jobs:
  Build-SCSS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/css/scss/main.scss
          destination: assets/css/main.css
      - name: Add and commit changes to branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Add compiled CSS files'
          git push
